-- ============================================
-- MIGRATION: Add features column + seed services data
-- Run this in your Supabase SQL Editor
-- ============================================

-- Add features column (PostgreSQL TEXT array)
ALTER TABLE services ADD COLUMN IF NOT EXISTS features TEXT[];

-- Seed all 19 existing services with their images and data
-- Uses ON CONFLICT to avoid duplicates if services already exist

INSERT INTO services (title, slug, description, long_description, icon, image_url, features, sort_order, is_active)
VALUES
  ('Thesis Typing', 'thesis-typing', 'Professional thesis typing with formatting and proofreading services for students.', 'When you need to type up a thesis, this can get complicated. Everything has to fall in place just right, the format has to be correct and there are many other details that can''t be missed either. If you are having trouble coming up with what you need to for your thesis paper, you can reach out for professional Fonet Stationary Center from our team.', 'fa fa-keyboard-o', '/images/service-thesis-typing.jpg', ARRAY['High-quality results with 99% accuracy','Additional research on demand','Done within 12 hours if needed','Affordable prices for students','Expert editing and proofreading included','Correct academic format and structure'], 1, true),
  ('Best Photocopy', 'photocopy-center', 'High-quality photocopying services up to A0 size, black and white and color.', 'We have a wide range of photocopy services including black & white and color copying. Our state-of-the-art equipment ensures crisp, clear copies every time.', 'fa fa-copy', '/images/service-photocopy.jpg', ARRAY['Black & white and color photocopying','Sizes from A4 up to A0','Single-sided and double-sided copies','High-speed bulk copying','Volume discounts available','Collating and stapling services'], 2, true),
  ('T-Shirt Print', 'tshirt-print', 'Custom T-shirt printing with your own designs, logos, and artwork.', 'Create custom T-shirts with your own designs, logos, and artwork. Whether it''s for a team event, corporate branding, school uniforms, or personal expression.', 'fa fa-tags', '/images/service-tshirt-print.jpg', ARRAY['Custom designs and logos','High-quality durable prints','Single piece or bulk orders','Multiple fabric colors available','Corporate branding solutions','Quick turnaround time'], 3, true),
  ('Cup/Plate Print', 'cup-plate-print', 'Personalized cup and plate printing for gifts, events, and corporate branding.', 'Make your events and gifts truly special with our personalized cup and plate printing service.', 'fa fa-coffee', '/images/service-cup-print.jpg', ARRAY['Full-color personalized printing','Perfect for corporate gifts and events','Wedding and birthday customization','Durable and long-lasting prints','Single piece or bulk orders','Various cup and plate sizes'], 4, true),
  ('Photo & Stickers', 'photo-stickers', 'High-quality photo printing and custom sticker production for any purpose.', 'From passport photos to large format prints, our photo printing service delivers exceptional quality.', 'fa fa-camera', '/images/sticker-printing-service.jpg', ARRAY['Passport and ID photos','Large format photo prints','Custom sticker design and cutting','Vinyl, paper, and transparent options','Waterproof sticker materials','Die-cut and kiss-cut stickers'], 5, true),
  ('Flex Print', 'flex-print', 'Large format flex banner printing for advertisements, events, and promotions.', 'Make a big impression with our large format flex banner printing service.', 'fa fa-picture-o', '/images/service-flex-print.jpg', ARRAY['Large format banner printing','Weather-resistant materials','Vibrant and durable inks','Indoor and outdoor banners','Custom sizes available','Grommets and finishing included'], 6, true),
  ('Lamination', 'lamination', 'Document and photo lamination in various sizes for protection and durability.', 'Protect your important documents, photos, certificates, and ID cards with our professional lamination service.', 'fa fa-shield', '/images/lamination.webp', ARRAY['Hot and cold lamination options','Matte and glossy finishes','Sizes from ID card to A0','Document and certificate protection','Photo lamination services','Tear and water resistant'], 7, true),
  ('Visiting Card', 'visiting-card', 'Professional visiting card design and printing services for individuals and businesses.', 'Make a lasting first impression with our professionally designed and printed visiting cards.', 'fa fa-address-card-o', '/images/service-visiting-card.jpg', ARRAY['Custom design services available','Multiple paper stock options','Matte, glossy, and textured finishes','Single and double-sided printing','Spot UV and embossing options','Fast turnaround on bulk orders'], 8, true),
  ('PVC Card', 'pvc-card', 'PVC ID card printing for organizations, schools, and individuals.', 'Professional PVC ID card printing for organizations, schools, colleges, and corporate offices.', 'fa fa-id-card', '/images/service-pvc-card.jpg', ARRAY['Durable PVC material','Full-color printing both sides','Photo integration','Barcode and QR code support','Bulk order discounts available','Custom design included'], 9, true),
  ('Self Stamp', 'self-stamp', 'Custom self-inking stamp design and production for business and personal use.', 'Create professional custom self-inking stamps for your business, organization, or personal use.', 'fa fa-circle', '/images/self stamp.jpg', ARRAY['Custom design and text','Self-inking mechanism','Various sizes and shapes','Thousands of impressions per refill','Quick turnaround time','Replacement ink pads available'], 10, true),
  ('Color Laser Print', 'color-print', 'High-quality color laser printing up to 12×18 size for all your printing needs.', 'Our color laser printing service delivers stunning, vibrant prints for all your needs.', 'fa fa-print', '/images/service-color-print.jpg', ARRAY['Vibrant color laser printing','Sizes up to 12×18 inches','Consistent color accuracy','Suitable for presentations and reports','Marketing materials and brochures','Volume pricing available'], 11, true),
  ('Ribbon Batch', 'ribbon-batch', 'Medal, ribbon, and batch printing for events, schools, and organizations.', 'Celebrate achievements and mark special occasions with our ribbon, batch, and medal printing service.', 'fa fa-bookmark', '/images/servicesimg.jpg', ARRAY['Custom ribbon printing','Medal and batch production','School and corporate events','Sports tournament awards','Custom text and logo printing','Various colors and sizes'], 12, true),
  ('Token of Love', 'token-of-love', 'Personalized gift items and token of love products for special occasions.', 'Express your feelings with our personalized Token of Love gift items.', 'fa fa-heart', '/images/servicesimg.jpg', ARRAY['Personalized photo gifts','Custom keychains and magnets','Photo frame customization','Birthday and anniversary specials','Gift wrapping available','Bulk orders for events'], 13, true),
  ('General Typing', 'general-typing', 'Accurate typing services for manuscripts, documents, forms, and all kinds of content.', 'Our typists are able to help with all forms of documents from business plans through to the creation of forms and templates for your business.', 'fa fa-file-text-o', '/images/service-thesis-typing.jpg', ARRAY['Manuscripts and books typing','Form creation and fillable PDFs','Business documents and reports','Legal document typing','Excel spreadsheets and presentations','Handwritten document conversion'], 14, true),
  ('Stationary', 'stationary', 'Complete range of stationary items for office, school, and personal needs.', 'Browse our complete collection of stationary items for all your office and school needs.', 'fa fa-pencil', '/images/servicesimg.jpg', ARRAY['Office supplies and accessories','School stationary items','Writing instruments','Filing and organization supplies','Art and craft materials','Competitive prices on all items'], 15, true),
  ('Documentations', 'documentations', 'Professional documentation and legal document preparation services.', 'We provide comprehensive documentation services including legal documents, contracts, agreements, and official paperwork preparation.', 'fa fa-folder-open-o', '/images/servicesimg.jpg', ARRAY['Legal document preparation','Contract and agreement drafting','Application form filling','Government form assistance','Certificate preparation','Proper formatting guaranteed'], 16, true),
  ('Notary Service', 'notary-service', 'Notary, attestation, translation, valuation, and document preparation support.', 'Fonet Stationary Center provides practical notary and document support for customers who need certified translations, attested copies, affidavits, sponsorship letters, property valuation assistance, audit-related documentation, and paper preparation.', 'fa fa-certificate', '/images/notary-public.jpg', ARRAY['Certified Nepali and English translation support','Notary and attested document stamp services','Affidavit, sponsorship, rent, and lease document support','Property valuation and audit documentation guidance','Document checklist review before submission','Online request option with document upload or drive link'], 17, true),
  ('Students Materials', 'students-materials', 'Study materials, notes, and academic support for students of all levels.', 'Supporting students at every level with comprehensive academic materials and services.', 'fa fa-graduation-cap', '/images/servicesimg.jpg', ARRAY['Term paper and thesis typing','Class notes compilation','Assignment formatting','Research proposal preparation','Book binding (spiral and ring)','Affordable student pricing'], 18, true),
  ('Courier Services', 'courier-services', 'Reliable courier and delivery services across Chitwan and nearby districts.', 'Our courier service provides reliable and timely delivery across Chitwan and neighboring districts.', 'fa fa-truck', '/images/servicesimg.jpg', ARRAY['Document delivery services','Package courier across Chitwan','Timely and reliable delivery','Safe handling of materials','Competitive delivery rates','Tracking capabilities available'], 19, true)
ON CONFLICT (slug) DO UPDATE SET
  description = EXCLUDED.description,
  long_description = EXCLUDED.long_description,
  icon = EXCLUDED.icon,
  image_url = EXCLUDED.image_url,
  features = EXCLUDED.features,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();
